#!/usr/bin/env bash
while true 

do 

echo
	echo "Write the name of you shell"

	echo "Example: bash, zsh, fish"

read -r -p "
 Choose an option : " shell

if [[ "$shell" != "bash" && "$shell" != zsh && "$shell" != fish ]]; then 

echo	
	echo "invalid shell name.... type exactly like: bash or zsh"
	echo "Warning! This is case sensitive"
echo

elif [ -f "/bin/$shell" ]; then

clear

echo	
	echo "shell found"
echo

else

clear

echo 
	echo "shell not found. $shell is not installed in your computer"
echo

fi
	done
